server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Ocultar versión de Nginx
    server_tokens off;

    # Cabeceras de Seguridad HTTP (Security Headers)
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), camera=(), microphone=()" always;

    # Compresión Gzip
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;

    # API → backend (gunicorn)
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 15m;
    }

    # Media (diseños e imágenes)
    location /media/ {
        alias /usr/share/nginx/media/;
        access_log off;
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    # Admin de Django + estáticos
    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /static/ {
        proxy_pass http://backend:8000;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}
