# Generated by Django 5.1.5 on 2026-07-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('linea', models.CharField(blank=True, choices=[('urbana', 'Urbana'), ('formal', 'Formal'), ('drinkware', 'Drinkware')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='ColorEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('hex', models.CharField(max_length=9, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='FotoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.URLField(max_length=500)),
                ('tipo', models.CharField(choices=[('ropa', 'Ropa'), ('vajilla', 'Vajilla')], max_length=10)),
                ('texto_review', models.TextField(blank=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=150)),
                ('producto_ropa_slug', models.CharField(blank=True, max_length=220)),
                ('producto_vajilla_slug', models.CharField(blank=True, max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_key', models.CharField(max_length=30, unique=True)),
                ('precio', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='TallaStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.PositiveIntegerField()),
                ('precio_oferta', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('nuevo', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('linea', models.CharField(choices=[('urbana', 'Urbana'), ('formal', 'Formal'), ('drinkware', 'Drinkware')], max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria')),
            ],
            options={
                'ordering': ('-creado_en',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.URLField(max_length=500)),
                ('es_principal', models.BooleanField(default=False)),
                ('es_frente', models.BooleanField(default=False)),
                ('es_reverso', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto')),
            ],
            options={
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='ProductoVajilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.PositiveIntegerField()),
                ('precio_oferta', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('nuevo', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('material', models.CharField(max_length=100)),
                ('capacidad_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('linea', models.CharField(default='drinkware', max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vajilla', to='catalogo.categoria')),
            ],
            options={
                'ordering': ('-creado_en',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenVajilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.URLField(max_length=500)),
                ('es_principal', models.BooleanField(default=False)),
                ('es_frente', models.BooleanField(default=False)),
                ('es_reverso', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.productovajilla')),
            ],
            options={
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('color_hex', models.CharField(max_length=9)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.producto')),
            ],
        ),
        migrations.CreateModel(
            name='VarianteVajilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('color_hex', models.CharField(max_length=9)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.productovajilla')),
            ],
        ),
    ]
