# Generated by Django 5.1.5 on 2026-07-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='imagenvajilla',
            name='imagen',
            field=models.CharField(max_length=500),
        ),
    ]
