# Generated by Django 5.1.5 on 2026-08-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='linea',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='linea',
            field=models.CharField(default='urbana', max_length=50),
        ),
        migrations.AlterField(
            model_name='productovajilla',
            name='linea',
            field=models.CharField(default='drinkware', max_length=50),
        ),
    ]
