# Generated by Django 5.1.5 on 2026-07-17 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('linea', models.CharField(max_length=20)),
                ('tipo_prenda', models.CharField(max_length=50)),
                ('talla', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.TextField()),
                ('presupuesto_estimado', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cotizada', 'Cotizada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.TextField(blank=True)),
                ('talla', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('prenda', models.CharField(blank=True, max_length=100)),
                ('color_base', models.CharField(blank=True, max_length=20)),
                ('linea', models.CharField(blank=True, max_length=20)),
                ('precio', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto_id', models.IntegerField(blank=True, null=True)),
                ('variante_id', models.IntegerField(blank=True, null=True)),
                ('diseno_id', models.IntegerField(blank=True, null=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.carrito')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('en_proceso', 'En proceso'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('catalogo', 'Catálogo'), ('diseno', 'Diseño')], max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.TextField(blank=True)),
                ('talla', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('prenda', models.CharField(blank=True, max_length=100)),
                ('color_base', models.CharField(blank=True, max_length=20)),
                ('linea', models.CharField(blank=True, max_length=20)),
                ('precio', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto_id', models.IntegerField(blank=True, null=True)),
                ('variante_id', models.IntegerField(blank=True, null=True)),
                ('diseno_id', models.IntegerField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
            ],
        ),
    ]
